"""add_background_sync_fields_to_daily_reports

Revision ID: a927927f25d6
Revises: 5fd7b6202e66
Create Date: 2026-08-02 20:29:39.708580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a927927f25d6'
down_revision: Union[str, Sequence[str], None] = '5fd7b6202e66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_office_reports', sa.Column('sync_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('daily_office_reports', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('daily_office_reports', sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('daily_office_reports', sa.Column('last_sync_error', sa.String(length=1000), nullable=True))
    op.add_column('daily_office_reports', sa.Column('sheet_row_number', sa.Integer(), nullable=True))
    op.alter_column('daily_office_reports','sync_status', server_default=None)
    op.alter_column('daily_office_reports','retry_count', server_default=None)

    op.create_index(op.f('ix_daily_office_reports_sync_status'), 'daily_office_reports', ['sync_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_office_reports_sync_status'), table_name='daily_office_reports')
    op.drop_column('daily_office_reports', 'sheet_row_number')
    op.drop_column('daily_office_reports', 'last_sync_error')
    op.drop_column('daily_office_reports', 'synced_at')
    op.drop_column('daily_office_reports', 'retry_count')
    op.drop_column('daily_office_reports', 'sync_status')
    # ### end Alembic commands ###
